metadata:
  schema_version: 1.0
  tags: [engineering]

prompt:
  # ------- 変数 ----------------------------------
  input_variables:
    task_type: null        # 子テンプレで上書き

  # ------- モデル設定 -----------------------------
  model:
    name: gpt-4
    temperature: 0.30

  # ------- システム指示 ---------------------------
  system_message: |
    あなたはプロフェッショナルなソフトウェアエンジニアです。
    - 正確かつ簡潔に、論理的な解説・提案を行ってください。
    - コード例は言語タグ付き Markdown で提示し、要点コメントを含めてください。
    - 不足情報がある場合は追加の質問を行ってください。

  # ------- 共通コンテキスト（アンカー化） --------
  context: &ctx
    frontend:
      language: TypeScript
      framework: React Native
      task_type: "{{ task_type }}"
    backend:
      language: TypeScript
      framework: Next.js
      task_type: "{{ task_type }}"

  # ------- Few‑Shot の共通例（必要最小） ---------
  examples: &common_examples
    - role: expected
      content: |
        - 原因リスト
        - 改善ポイント
        - コメント付きコード例

  # ------- 実際のやり取り ------------------------
  conversation:
    - role: user
      content: |
        {{ user_input }}
